name: "Build & Fill Cache"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install nix
      uses: cachix/install-nix-action@v17
    - name: Setup Cache
      uses: cachix/cachix-action@v10
      with:
        name: nix-dabei
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build kexec
      run: nix build -L .#kexec
    - name: Show size
      run: du -Lh  result/*
