name: "Build & Fill Cache"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install nix
      uses: cachix/install-nix-action@v18
    - name: Setup Cache
      uses: cachix/cachix-action@v12
      with:
        name: nix-dabei
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build kexecTarball
      run: |
        nix build -L .#kexecTarball

    - name: Show kexecTarball size
      run: du -Lh  result/*

    - name: Upload release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          result/nixos-kexec-installer-x86_64-linux.tar.gz
